on:
  push:
    # branches: [master]
  workflow_dispatch:

name: 🚀 Deploy
jobs:
  build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Verify build
        run: ls -la public

      - name: List output files
        run: find public/ -print

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: test/
